### ISSUE TITLE
.c files missing from repository

### ISSUE THREAD

**Issue by loopless** [eleme/thriftpy#105]
I am trying to build on Windows and files such as transport/cybase.c are missing from the repository.

**Comment by lxyu** [comment]
@loopless the `.c` files were generated by cython, if you want to build from source, you have to install cython first.

**Comment by loopless** [comment]
OK, thanks. 
I was just trying "python setup.py build" and got no messages about missing cython, simply missing .c files.

**Comment by lxyu** [comment]
Yah it is, we don't include the `cython` to requirements since you can install `thriftpy` by `pip install thriftpy` without `cython`.
