### ISSUE TITLE
Upstream compatiable Multiplexing protocol

### ISSUE THREAD

**Issue by lxyu** [eleme/thriftpy#114]
Original discussed here at #88 

The Apache Thrift implementation is different from the current implementation of thriftpy: https://issues.apache.org/jira/browse/THRIFT-563

**Comment by xvblack** [comment]
I created a patch to TMultiplexingProcessor which take in an additional service_name argument and register the processor directly using the given service_name.

To connect to a TMultiplexingProcessor, TMultiplexingProtocol should be used, which takes a underlying protocol and the service_name for the remote service. When writing new message header, it joins the service_name and function name as the new api, which will be decoded by TMultiplexingProcessor. The current separator is ":".

This should be compatible with the https://issues.apache.org/jira/browse/THRIFT-563 solution.

**Comment by GuoJing** [comment]
yes, I need this, thank you @xvblack

**Comment by lxyu** [comment]
Solved in #117

**Comment by bufferoverflow** [comment]
and compatible with this: https://issues.apache.org/jira/browse/THRIFT-1914
