### ISSUE TITLE
Server closed unexpected 

### ISSUE THREAD

**Issue by GuoJing** [eleme/thriftpy#118]
If client and server have different transport, exp, server side using `TFramedTransportFactory`, client using `TBufferedTransportFactory`, if client send buff to server, server will closed unexcepted, with no exception.

In fact, In thriftpy socket.py read() method, it will read 0 bytes and raise exception. But server should not closed.

**Comment by lxyu** [comment]
Fixed in #119

**Comment by GuoJing** [comment]
Love it, thank you.
