### ISSUE TITLE
Need faster parser

### ISSUE THREAD

**Issue by moonshadow** [eleme/thriftpy#126]
Hi~ The parser is fucking too slow now, which takes several minutes for a large thrift file, would you try to do any efforts to improve this? Thanks.

**Comment by hit9** [comment]
Profile result is required, thx

**Comment by hit9** [comment]
I tested `load` with a thrift file (3000 lines), cost 250ms.

**Comment by lxyu** [comment]
@moonshadow yeah, would like to see the benchmark thrift files and codes.
