### ISSUE TITLE
binary type in python3 transtered as b'\x..', which cannot be interpreted as other languages

### ISSUE THREAD

**Issue by lspvic** [eleme/thriftpy#130]
I transfer a binary  from python to java,  the python side use thriftpy with python3.4, when i get with java, the bianry it's the b'...' format.
How could it fixed for python3?

**Comment by lxyu** [comment]
what's the protocol and transport used in thriftpy and java? do them match?

**Comment by lxyu** [comment]
It looks like a proto mismatch error.

Feel free to re-open it if you have more information, thanks.
