### ISSUE TITLE
Add camelCase methods to support drop-in replacement of thrift

### ISSUE THREAD

**Issue by laserson** [eleme/thriftpy#135]
In an effort to support both python 2 and 3, I am trying to use both the Apache Thrift python package and thriftpy.  One thing that makes it more difficult is that method names have been changed from the Apache camelCase to the more pythonic snake_case.  However, it would be convenient to have camelCase versions available so that I don't have to check the python version each time I want to invoke a method.

For example, `thriftpy.transport.buffered.cybuffered.TCyBuffered.is_open` while the Apache version would generate an `isOpen` method.

Thoughts?

**Comment by lxyu** [comment]
We once used python sdks from both Apache Thrift and thriftpy internally for some time. In our situation, we wrap the `client`, so only the api calling part, such as `client.ping()` is opened to the outside, and the codes will stay the same.

I've considered this problem when developing the lib. The thriftpy was a rewrite based on 'pythonic thinking', so many code actually (including apis) differs from the upstream. Take `TBinaryProtocol` for example, the useless methods were all removed, and the read/write struct logic have a slight difference too.

The camelcase is one of many unpythonic things, if I keep the camelcase style, there will be snake_case and camelCase code mixed together in this lib. And keep the camelCase also means make the `interface` thing 100% compatiable with Apache Thrift, but the `interface` itself is just not pythonic, it's designed for java. When the `interface` is not 100% kept same in thriftpy, you'll find both lib have some unique methods, then the camelCase is not that important anymore.

So my suggestion is wrap the `client` and only expose that to your clients.

**Comment by laserson** [comment]
k, I'll close this issue.  Thanks!
