### ISSUE TITLE
Support TSSLSocket

### ISSUE THREAD

**Issue by laserson** [eleme/thriftpy#136]
Currently supported by `thrift` but not `thriftpy`.

**Comment by amontalenti** [comment]
Mentioned by Wes McKinney (author of Pandas) here: https://twitter.com/wesmckinn/status/672638289560539136 (he works on Ibis at Cloudera now)

**Comment by lxyu** [comment]
Yah we see it, hopefully we'll support it soon.

**Comment by lxyu** [comment]
SSLSocket supported now, it's actually more difficult than the first glance. The implementation in thriftpy should be better than the upstream apache lib:

1. more secure. it use the latest `create_default_context` with more secure default options, and has a limited backward compat implementation ported to py26 and py33. For more info refer to the source code of CPython ssl lib, https://github.com/python/cpython/blob/3.5/Lib/ssl.py#L425-L471 , the current apache implementation has none of these.

2. more feature rich. you can customize or persist the `SSLContext` object to suit your needs.

While on the other hand, security is difficult and I'm not a security expert. I tried to implement the SSL socket based on best practice, it may still be bugs in it.

So you may want to review the code before use, and I'll appricate any feedbacks on the implementation.

**Comment by amontalenti** [comment]
@lxyu Very cool! I'm going to take a look next week. I also tweeted at Wes to let him know.

**Comment by lxyu** [comment]
@amontalenti Thanks, I'll make a release as long as the review finished!

**Comment by lxyu** [comment]
Close as released in v0.3.3
