### ISSUE TITLE
We have lots of this error

### ISSUE THREAD

**Issue by GuoJing** [eleme/thriftpy#137]
I don't know why, maybe client has something wrong with closing the socket?

![2015-06-02 18 19 22](https://cloud.githubusercontent.com/assets/363073/7933764/1e23080e-0954-11e5-9cb8-115c48aadd2a.png)

But the server always raise this exception.

**Comment by lxyu** [comment]
Do you use gevent?

**Comment by GuoJing** [comment]
@lxyu oh, yes. another question, why only close when platform is darwin and freebsd? thanks.

**Comment by lxyu** [comment]
Gevent behaves weird under high load, I think it may be related to some greenlets get starved. We've also see lots of weird errors when gevent enabled, especially under very high load, but the error percentage is very small.

So my suggestion is keep the load lower and ignore them as long as the percentage is very small, or don't use gevent.
