### ISSUE TITLE
Recursive structs no longer supported

### ISSUE THREAD

**Issue by gladhorn** [eleme/thriftpy#144]
Thrift structures referencing themselves are no longer supported.

```struct RecursiveType {
    1: string data,
    2: list<RecursiveType> tree
}```

used to work with Thriftpy 0.1.15 but do no longer work with 0.3.1.
This is a regression. Sadly the official Python thrift bindings also don't support this. Other language bindings do though.

**Comment by lxyu** [comment]
@hit9

**Comment by hit9** [comment]
Thrift is not like C, this feature is currently not in use (in our company).

@lxyu, should we implement it?

**Comment by hit9** [comment]
@gladhorn And... Pull request accepted..

**Comment by hit9** [comment]
We are ready to accept the "recursive structs definition" now.
