### ISSUE TITLE
Pull out parser

### ISSUE THREAD

**Issue by breerly** [eleme/thriftpy#147]
I'd love to reuse just the parse without forking; what do you guys think?

Perhaps we can move it to a package called `thriftpy-parser`.

**Comment by breerly** [comment]
I suppose I could just use https://github.com/wickman/ptsd ... seems like the activity on this repo is much higher though *sigh*

**Comment by hit9** [comment]
Hi, @breerly  you just can use thirftpy's parser.

**Comment by breerly** [comment]
@hit9 not without installing all of thriftpy - that's the whole point. I'm not able to use JUST the parser without forking. No?

**Comment by lxyu** [comment]
@breerly sorry we don't see the need of seperate the parser and maintain it seperately.

I think you can fork the repo, the parser is pretty stable as the thrift IDL is not changing. So you can just move that part to your codebase.

Thanks!
