### ISSUE TITLE
New thriftpy release with latest commits/PR's?

### ISSUE THREAD

**Issue by amontalenti** [eleme/thriftpy#164]
Hi @hit9 and @lxyu, I was wondering if you were planning for a new thriftpy release soon with the latest commits/PR's?

In particular, we would like to start relying upon the `load_fp` API added in #153, but since we plan to include functionality for this in another open source module, we'd like to depend upon a specific released version of thriftpy. Thanks for all your help!

**Comment by lxyu** [comment]
ok, I'll release a new minor version tonight. : )

**Comment by lxyu** [comment]
v0.3.2 released.
