### ISSUE TITLE
Logger naming

### ISSUE THREAD

**Issue by c4urself** [eleme/thriftpy#165]
Would you be open to a pull requests that uses named loggers instead of using the root Logger? My suggestion is to add:

```
import logging
logger = logging.getLogger(__name__)`
logger.info('hi there')
```

instead of 

```
import logging
logging.info('hi there')
```

This allows any logs emitted by the module to be tracked back to the module; additionally we can suppress logs easily on a per-module basis. This matches the apache/thrift implementation as well.

**Comment by drudim** [comment]
+1

**Comment by lxyu** [comment]
+1, It's great~
