### ISSUE TITLE
HTTP Server Example

### ISSUE THREAD

**Issue by smakhtin** [eleme/thriftpy#166]
Hello. I want to use thriftpy as a thrift server for JS thrift client with HTTP transport. I found example for standard thrift library, but cannot find anything similar for thriftpy.

**Comment by joan2015** [comment]
the same question , how to create a thrift server with HTTP transport ?

**Comment by keitheis** [comment]
Hi @smakhtin @joan2015, you might want to try my http branch: https://github.com/eleme/thriftpy/pull/208

**Comment by lxyu** [comment]
#208 merged.

**Comment by keitheis** [comment]
Thanks!
