### ISSUE TITLE
Java ProcessBuilder.inheritIO not working with thriftpy

### ISSUE THREAD

**Issue by marekjagielski** [eleme/thriftpy#170]
I posted originaly description of my problem here: http://stackoverflow.com/questions/33769080/processbuilder-inheritio-not-working-when-python-with-thread-setdaemon

I am running python application from Java.  I established two-way communication between Java and Python.
I wrote in my Java code pb.inheritIO() to redirect python prints to standard output. And redirection is not working.

I made a workaround by overloading handle method of TThreadedServer. 
In while loop I forced flushing streams:

        while True:
            self.processor.process(iprot, oprot)
            sys.stdout.flush()
            sys.stderr.flush()

Could it be a valid solution to be integrated into thriftpy?

**Comment by lxyu** [comment]
I'm not very clear about the problems, it seems you're trying to capture the stdout output from python server and redirect them to java, so I'll try to discuss this problem here:

1. what method do you use to print to console, the logger with logging config or the raw print function?
2. If you run the python server daemon directly from console, is there any output?

I guess it may be related to python deamonize and stdout issue, you may check these links first: 
https://stackoverflow.com/questions/13180720/maintaining-logging-and-or-stdout-stderr-in-python-daemon
http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/

**Comment by marekjagielski** [comment]
Hi,
1. Yes, I use raw print('Hello') method.
2. I tried repoducing situation here: https://github.com/marekjagielski/python-from-java
Uncommenting line: sys.stdout.flush() in:
https://github.com/marekjagielski/python-from-java/blob/master/src/main/resources/python/from/java/Main.py
makes print appearing.

It is why I overrode method "handle" of TThreadedServer:
```python
def custom_handle(self, client):
    itrans = self.itrans_factory.get_transport(client)
    otrans = self.otrans_factory.get_transport(client)
    iprot = self.iprot_factory.get_protocol(itrans)
    oprot = self.oprot_factory.get_protocol(otrans)
    try:
        while True:
            self.processor.process(iprot, oprot)
            sys.stdout.flush()
            sys.stderr.flush()

    except TTransportException:
        pass
    except Exception as x:
        logging.exception(x)

    itrans.close()
    otrans.close()
```

**Comment by lxyu** [comment]
Thanks for the reproducing script!

I simplified the reproduce script at https://gist.github.com/lxyu/1c1c15e57cde9e49dd17

If you save the file as test.py file, and execute it in terminal, the output is continuing, but if you try to pipe the output, for example `python test.py | grep handle`, you'll find it shows all lines at the same time, after the script ends.

I'd suggest you use the logging module instead, it's also in the gist link.

**Comment by lxyu** [comment]
Close as not really a thriftpy issue and should be solved now.

**Comment by marekjagielski** [comment]
Thanks for response. My problem is that python process is executing users code: http://systemincloud.com/tasks/#0.8.0/commons/pythontask . It is more than sure that for test purpose they will need raw print. I will rethink it a little bit.
Thanks,
