### ISSUE TITLE
Options for calling make_server() with different T*Server

### ISSUE THREAD

**Issue by anhldbk** [eleme/thriftpy#174]
I used thriftpy in production. But under high load, I noticed that my server didn't fully utilize all available CPU cores .
After that I used TForkingServerServer instead. The performance's sharply improved. All cores were fully utilitized.

I think it's great to support different T*Server when calling make_server(). What do you guys think?

**Comment by lxyu** [comment]
The `make_server` is only a 10 line method, it's here for convinience and demo.

When used in high load server, you can easily customize your own TServer implementation and `make_server` function. You may also refer to `examples/gunicorn_thrift` for how to use TServer with `gevent` and `gunicorn`, which has much less overhead than ForkingServer.

**Comment by lxyu** [comment]
But I think a kwargs to server class benifits too, we'll add the kwarg later.

**Comment by anhldbk** [comment]
Well thank you @lxyu for showing me a better approach.

**Comment by anhldbk** [comment]
@lxyu To use Thrift in high load servers, have you got any recommendation? Use only Thrift or Thrift+GUnicorn?

**Comment by lxyu** [comment]
We're using thriftpy + gunicorn + gevent together, you may want to check https://github.com/eleme/gunicorn_thrift

**Comment by anhldbk** [comment]
@lxyu Pls forgive me for my inadequate understanding
In my case, I have applications running at back-end. Binary protocols are much preferred. As I know Gunicorn only serves Http requests. How my binary-protocol-only clients can work with such services?

**Comment by lxyu** [comment]
Yah, using gunicorn do not mean to use http. You can imagine the protocol is also modular and can be replaced.

The default TForkingServer will fork a new process on every request, which is a big overhead consider the request traffic volumn. The gunicorn is very efficent at handling the requests with multiple workers (multiprocessing).

For more understanding you may want to read the source code at `gunicorn_thrift` project, the implementation of `SyncThriftPyWorker` and `ThriftApplication` is recommended. Also try to run the examples, it'll help too.

**Comment by anhldbk** [comment]
@lxyu Thank you so much! I'll try it.
