### ISSUE TITLE
Converter Between Json and Thrift Struct

### ISSUE THREAD

**Issue by xuanyuanking** [eleme/thriftpy#180]
In my project I need a converter between standard json and thrift struct. So I implemented a generic one based on thriftpy. Like convert the json below:
``` python
{
    "test_simple_map": {
        "a": 1,
        "b": 2
    },
    "name": "abc",
    "add_more": {
        "more": "more"
    },
    "error_type": "SUCCESS",
    "in_list": [
        {
            "l_name": "l_name1"
        },
        {
            "l_name": "l_name2"
        },
        {
            "l_name": "l_name3"
        }
    ],
    "test_struct_map": {
        "a": {
            "value": "abc"
        },
        "b": {
            "value": "abc1"
        }
    },
    "num": 128,
    "simple_list": [
        1,
        2,
        3,
        4
    ],
    "desc": "for_lyj_test"
}
```
To the thrift struct:
``` python
meta(test_simple_map={u'a': 1, u'b': 2}, name=u'abc', add_more=in_meta(in_list=None, more=u'more'), error_type=1, in_list=[list_test(l_name=u'l_name1'), list_test(l_name=u'l_name2'), list_test(l_name=u'l_name3')], test_struct_map={u'a': test_map_value(value=u'abc'), u'b': test_map_value(value=u'abc1')}, num=128, simple_list=[1, 2, 3, 4], desc=u'for_lyj_test')
```
And also convert back to json. details: https://github.com/xuanyuanking/thrift_json_convertor

If you think it's necessary, I'm glad to give a PR about this.

Thanks!

**Comment by wooparadog** [comment]
Hi, actually we are using http/json as part of our protocol which is implemented in https://github.com/eleme/thriftpy/pull/132/, but it's too specific for our needs so we didn't merge it into thriftpy itself.

We don't want to depart from Apache upstream too far, I'm afraid we can't take your proposal. 

@lxyu What's your idea?

**Comment by xuanyuanking** [comment]
@wooparadog 
Thanks for your reply :) 
I think this util is just for converting between standard json and thrift structs, it's not conflict with the thrift transport protocol, and I implement this maily based on thriftpy's meta struct, so I think if we can merge it into thriftpy will be better.
The usage in product like:
``` python
meta_struct = utils._client_proto.TDatasetMeta() # thrift struct TDatasetMeta
ret_struct  = None
utils.json_thrift_convertor(self.__request_data, meta_struct)
self.user_struct = utils._client_proto.common.TUser()
utils.json_thrift_convertor(user_struct, self.user_struct)
try:
    # createDataset method definition:
    #     TDatasetDetail createDataset(1:common.TUser user, 2:TDatasetMeta datasetMeta) throws (1: common.TMasterException e);
    ret_struct = self.__client.createDataset(self.user_struct,
    meta_struct) 
except utils._client_proto.common.TMasterException as e:
    ...
```

**Comment by lxyu** [comment]
@xuanyuanking Thanks for you time and contribution, however I also think it's not very suitable for merge due to these two reason:

1. Thrift struct is more flexible than json, for example json dict key type is limit to string. So there do not exist a simple mapping between json and thrift without introducing `protocol`.
2. The converter itself can be more generic, you can implement a converter between all protocols (build in or customized protocols) with thrift struct.

There're 2 helper function in the `thriftpy.utils` that may help in implementing the converter. I used your thrift file to make the following example:

```python
test_thrift = thriftpy.load("test.thrift", module_name="test_thrift")
test_thrift_obj = meta(add_more=in_meta(in_list=None, more='more'), error_type=1, test_struct_map={'a': test_map_value(value='abc'), 'b': test_map_value(value='abc1')}, simple_list=[1, 2, 3, 4], test_simple_map={'a': 1, 'b': 2}, num=128, in_list=[list_test(l_name='l_name1'), list_test(l_name='l_name2'), list_test(l_name='l_name3'), list_test(l_name='l_name4')], name='abc', desc='for_lyj_test')

serialize(test_thrift_obj, proto_factory=TJSONProtocolFactory())
# b'\x00\x00\x01\xc2{"metadata": {"version": 1}, "payload": {"add_more": {"more": "more"}, "test_struct_map": [{"value": {"value": "abc"}, "key": "a"}, {"value": {"value": "abc1"}, "key": "b"}], "in_list": [{"l_name": "l_name1"}, {"l_name": "l_name2"}, {"l_name": "l_name3"}, {"l_name": "l_name4"}], "name": "abc", "desc": "for_lyj_test", "error_type": 1, "simple_list": [1, 2, 3, 4], "test_simple_map": [{"value": 1, "key": "a"}, {"value": 2, "key": "b"}], "num": 128}}'
```

It produce a similar json string that can be `deserialize` back to thrift struct. If you want to make it more cleaner to be readable in json lib, it's easy to customize a new json protocol to fit the needs.
