### ISSUE TITLE
error with example

### ISSUE THREAD

**Issue by bothwellw** [eleme/thriftpy#182]
Hi

I have install thriftpy version 0.3.4 , Pyhton 2.7.9 on Ubuntu

I am trying the pingpong example in the documentation and I am getting this error

no handlers could be found for logger thriftpy.server

I tried n windows and I am getting the same error

**Comment by wooparadog** [comment]
You should configure python logging module first, we don't know how you need to configure your logger, so we didn't include it in our code. And it doesn't affect anything other than logging.

You can run `logging.basicConfig()` at the head of your code to avoid this message, but I still recommend you to take a look at how to configure logging.

**Comment by bothwellw** [comment]
Thanks its working now
