### ISSUE TITLE
Compact protocol not part of 0.3.5 release

### ISSUE THREAD

**Issue by zelenij** [eleme/thriftpy#187]
Good time of day,

I see that support for compact has been added, which is great news.  However, the latest release doesn't seem to include it.  Is it because it isn't ready yet?  Or it was simply delayed until the next release?

**Comment by wbolster** [comment]
a new release would be great. looks like it's the only blocker for porting happybase to thriftpy: https://github.com/wbolster/happybase/pull/114

**Comment by lxyu** [comment]
Included in [v0.3.6](https://github.com/eleme/thriftpy/releases/tag/v0.3.6)
