### ISSUE TITLE
force bytes

### ISSUE THREAD

**Issue by wbolster** [eleme/thriftpy#190]
is it possible to force an api to return `bytes` instead of the messy mix of `str` (`unicode` in py2) and `bytes`, depending on whether the value happened to be valid `utf-8`?

apache hbase has a bytes-only data model, and happybase, the python library for it, uses thrift to communicate with hbase. however, this results in mixed `str`/`bytes` responses:

```python
>>> c = happybase.Connection()
>>> t = c.table('mytable')
>>> t.put(b'\x01\x02', {'cf2:foo\xee\xee\xee': '\xff\xff\xff'}
>>> t.put('foo', {'cf1:bar': u'baz'})
>>> list(t.scan())
[(u'\x01\x02', {'cf2:foo\xee\xee\xee': '\xff\xff\xff'}),
 (u'foo', {u'cf1:bar': u'baz'})]
```

(this example code was run with python2)

**Comment by lxyu** [comment]
You can now add `decode_response=False` to protocol factory to force return bytes.

**Comment by wbolster** [comment]
awesome, thanks.
