### ISSUE TITLE
Errors Pickling classes imported through thriftpy

### ISSUE THREAD

**Issue by adambullmer** [eleme/thriftpy#191]
It currently isn't possible to pickle some classes imported through thriftpy.

Issues arise as the pickler function can't import the class module.

```py
import pickle
from mythrift.models.thing_models import Thing
pickle.dumps(Thing)
```
Results in this error message: `PicklingError: Can't pickle <class 'thing_models.Thing'>: import of module 'thing_models' failed`

**Comment by lxyu** [comment]
Can't reproduce. May you provide a full reproduce script?

And did you provide a `module_name` when load thrift file, it's described here https://thriftpy.readthedocs.org/en/latest/#better-module

**Comment by adambullmer** [comment]
Yeah, looks like it was because I was importing the thrift models like I would any other python module. When I loaded them as described with that link, pickle had no problems.
