### ISSUE TITLE
implementation for "unhashable" is wrong

### ISSUE THREAD

**Issue by wbolster** [eleme/thriftpy#192]
The implementation to make a class unhashable which has been added in #184 is wrong. See commit daa213d719743bf2e0f1db0d972ee622bc69102c for the changes.

The python data model docs at
https://docs.python.org/3/reference/datamodel.html#object.__hash__ state:

> ```A class that overrides __eq__() and does not define __hash__() will have its __hash__() implicitly set to None. When the __hash__() method of a class is None, instances of the class will raise an appropriate TypeError when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking isinstance(obj, collections.Hashable).```

Instead of raising a `TypeError` from `__hash__()`, the method should not be present at all, and a `__hash__ = None` should be in its place, like this:

```python
class SomeClass(...):
    __hash__ = None

    def __eq__(self, other):
        ...
```

**Comment by lxyu** [comment]
should be resolved in https://github.com/eleme/thriftpy/commit/9e5a86300bfa6850a8839226010b6dd78eff0b51
