### ISSUE TITLE
Can't support nuitka?

### ISSUE THREAD

**Issue by pamxy** [eleme/thriftpy#199]
Is thriftpy can't support nuitka? Run the generate .exe, and throw thriftpy\_compat.py line 87, in _ _init_ _ def init(self): SystemError: unknown opcode

**Comment by pamxy** [comment]
I suppose the problem is occurring thriftpy.load() function.

**Comment by lxyu** [comment]
Can you provide a reproduce script and the error log?

**Comment by pamxy** [comment]
calc_client.py
`#!/usr/bin/python
# -*- coding: utf-8 -*-
__author__ = 'guipengliang'
#encoding=utf-8

import sys
import datetime
import time

#sys.path.append('/home/pamxy/Workspace/Python/calculator')
#sys.path.append('/home/pamxy/Workspace/Python/calculator/thriftpy')

#pprint.pprint(dict(os.environ))
print('sys.version:%s'%sys.version)
print('sys.path:%s'%sys.path)

print('import thriftpy')
import thriftpy



#from thriftpy.protocol import TCyBinaryProtocolFactory
#from thriftpy.transport import TCyBufferedTransportFactory
print('from thriftpy.rpc import client_context')
from thriftpy.rpc import client_context

print("calc_thrift=thriftpy.load('calc.thrift',module_name='calc_thrift')")
calc_thrift=thriftpy.load('calc.thrift',module_name='calc_thrift')

thriftpy.install_import_hook()

from calc_thrift import Calculator as CalculatorService

from thriftpy.parser.parser import parse
note_thrift = parse("calc.thrift")
print('note_thrift:%s'%note_thrift)
print('note_thrift.Calculator:%s'%note_thrift.Calculator)

print('CalculatorService:%s'%CalculatorService)

print('calc_thrift:%s'%calc_thrift)
print('calc_thrift.Calculator:%s'%calc_thrift.Calculator)
print('type(calc_thrift.Calculator.mult_args):%s'%type(calc_thrift.Calculator.mult_args))
print('calc_thrift.Calculator.mult_args:%s'%calc_thrift.Calculator.mult_args)
# print('type(calc_thrift.Calculator.mult_args()):%s'%type(calc_thrift.Calculator.mult_args()))
# print('calc_thrift.Calculator.mult_args():%s'%calc_thrift.Calculator.mult_args())

def main():
    print('begin')
    main_begin=datetime.datetime.now()
    print('client_context')
    with client_context(calc_thrift.Calculator,'127.0.0.1',6000,
    #with client_context(calc_thrift.Calculator,'192.168.88.101',6000,
                        #proto_factory=TCyBinaryProtocolFactory(),
                        #trans_factory=TCyBufferedTransportFactory(),
timeout=None,socket_timeout=None,connect_timeout=None) as cal:
        mult_begin=datetime.datetime.now()
        print('a=cal.mult(5,2)')
        a=cal.mult(5,2)
        mult_end=datetime.datetime.now()
        print('mult:%s'%(mult_end-mult_begin))

        print('a:%s'%a)
        # b=cal.sub(7,3)
        # # print('b:%s'%b)
        # c=cal.sub(6,4)
        # # print('c:%s'%c)
        # d=cal.mult(b,10)
        # # print('d:%s'%d)
        # e=cal.add(a,d)
        # # print('e:%s'%e)
        # f=cal.div(e,c)
        # print(f)
    main_end=datetime.datetime.now()
    print('main:%s'%(main_end-main_begin))

if __name__ == '__main__':
    main()
    pass
`

calc.thrift
`
#Calculator service
service Calculator{
    i32 add(1:i32 a,2:i32 b);
    i32 sub(1:i32 a,2:i32 b);
    i32 mult(1:i32 a,2:i32 b);
    i32 div(1:i32 a,2:i32 b);
}`

client_build.bat
`
nuitka --mingw --recurse-all  --show-modules --debug calc_client.py

pause`

linux is the same!

**Comment by lxyu** [comment]
thriftpy does some 'dark magic' thing on `function.__code__` method, and it seems nuika is another python compiler that runs on Windows? If so, sorry we don't officially support it, please use official CPython if you have any problem.

**Comment by pamxy** [comment]
Well, thank you, I have to use thrift.
