### ISSUE TITLE
lack of server type

### ISSUE THREAD

**Issue by dozysun** [eleme/thriftpy#200]
thriftpy only support TThreadedServer but it still limited on server handler func concurrent because of GIL, is there any plan to support a real concurrent server type to support heavy handler func, eg: multiprocess,

**Comment by lxyu** [comment]
you may want to check out this repo: https://github.com/eleme/thrift_connector

**Comment by dozysun** [comment]
this solution doesn't work for me,  i have a log runtime task run on server side,  and multi client  send tasks , i want improve efficiency on server

**Comment by lxyu** [comment]
sorry this is the correct link: https://github.com/eleme/gunicorn_thrift

**Comment by lxyu** [comment]
Gunicorn can manage multi process very efficiently, if you have many IO related task, also enable the Gevent for better performacne.

**Comment by dozysun** [comment]
![image](https://cloud.githubusercontent.com/assets/8655323/15176468/cd4d0f66-179d-11e6-95d2-1b2cd5d38298.png)

i have run a test on gunicore_thrift but lt still works orderly,  not as i expected

**Comment by dozysun** [comment]
oh, i find out that because of i use one way( oneway void sleep(1: i32 seconds))  that makes  it didn't works concurrently,  use normal request works fine. will it be matter to make oneway works fine with gunicorn_thrift?

**Comment by dozysun** [comment]
oh, it seems my problem to  use one client  send multi one way func( oneway void sleep(1: i32 seconds)),
use multi client it's works fine , thanks very much.
