### ISSUE TITLE
Clients in other languages?

### ISSUE THREAD

**Issue by imperio-wxm** [eleme/thriftpy#201]
Hi, I want to make a server by thriftpy, but a client using other languages, such as java or js.
Is there any problems?

I meanings your client need to load ".thrift" file like:
```python
import thriftpy
pingpong_thrift = thriftpy.load("pingpong.thrift", module_name="pingpong_thrift")

from thriftpy.rpc import make_client
```
Other languages need to do same things or not?

**Comment by lxyu** [comment]
On other language you can use the Apache Thrift to generate client sdk, they're compatible if you're using the same protocol and transport.
