### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by imperio-wxm** [eleme/thriftpy#204]
Hi,how can I set timeout in thriftpy?

I whrite like:

```python
with client_context(dd_thrift.DingService, '127.0.0.1', 9090, proto_factory=dd_factory,
    socket_timeout=5000,connect_timeout=5000) as c:
```

But error:

```python
UserWarning: `timeout` deprecated, use `socket_timeout` and `connect_timeout` instead.
warnings.warn("`timeout` deprecated, use `socket_timeout` and "
..........
..........
File "/usr/local/lib/python2.7/dist-packages/thriftpy/transport/socket.py", line 108, in read
buff = self.sock.recv(sz)
socket.timeout: timed out
```

Thanks!

**Comment by MrKiven** [comment]
Of course you can.
It seems like your service down..

**Comment by imperio-wxm** [comment]
@MrKiven 
I am not sure set timeout in my server or client or both?

**Comment by MrKiven** [comment]
client

**Comment by imperio-wxm** [comment]
@MrKiven 

My server is fine,but client set socket_timeout=5000 or 5000+ does not work, it is also default 3000.

When I count 3s, time out error come out.

**Comment by MrKiven** [comment]
server side default timeout is 3s, @lxyu

**Comment by imperio-wxm** [comment]
@MrKiven 
When I use param like “timeout”,works!, but I notice warning:
```python
UserWarning: `timeout` deprecated, use `socket_timeout` and `connect_timeout` instead.
```
timeout really deprecated?

**Comment by MrKiven** [comment]
yes, will use `socket_timeout` and `connect_timeout`, but if you set `timeout`, it also works

**Comment by imperio-wxm** [comment]
@MrKiven 
thriftpy 0.3.8

**Comment by AllanDaemon** [comment]
I changed the default `client_timeout` in `thriftpy/transport/socket.py` from `3000` to `None` and now my server is working as expected, just like Apache implementation.

from:
```
class TServerSocket(object):
    """Socket implementation for server side."""

    def __init__(self, host=None, port=None, unix_socket=None,
                 socket_family=socket.AF_INET, client_timeout=3000,
                 backlog=128):
```

to:
```
class TServerSocket(object):
    """Socket implementation for server side."""

    def __init__(self, host=None, port=None, unix_socket=None,
                 socket_family=socket.AF_INET, client_timeout=None,
                 backlog=128):
```

I see I have the option to pass the timeout when creating a service manually. But the function `make_server` in `thriftpy/rpc.py` uses the default parameter for this. I didn't read all the source to figure out where to fix this. One option is passing explicitly `client_timeout=None` when creating the `TServerSocket` in `make_server` function. But It seems to me that the correct approach is setting the default timeout in the `TServerSocket` class initialization.

**Comment by AllanDaemon** [comment]
These 2 commits fixed it to me.
https://github.com/AllanDaemon/thriftpy/commit/6a4b118ab324b404bccf6358a7f0607ce805ef01
https://github.com/AllanDaemon/thriftpy/commit/0944247a8211f806c185472638dc411d43a14931

I running tests and I will write some tests for it latter before I make pull request. Does this solutions sounds ok?

**Comment by lxyu** [comment]
Sorry for the late reply, the issue is because the `client_timeout` default set to 3000ms and the setting was not exposed in `make_server` helper function.

You may now pass the `client_timeout=None` to force the server side never timeout a client socket.

If it doesn't resolve your issue, feel free to reopen this thread.

**Comment by ghost** [comment]
Hello. I have thriftpy version 0.3.9 and collided with bug like @AllanDaemon report. As advised above, I replaced the value of client_timeout to None. And it worked. In this regard, I have a question. Maybe it makes sense to initially set the value to None? Thank you for attention.
