### ISSUE TITLE
Default List Value

### ISSUE THREAD

**Issue by mponza** [eleme/thriftpy#207]
Hi! I'm using thriftpy 0.3.8 and I have a problem in appending elements to a list, which is set by default value in the thrift file.

Thrift file:

    struct Document {
        1: list<i32> sentences = [],
    }

    struct EnhancedDocument {
        1: i32 id,  
        2: Document title,
        3: Document headline,
        4: Document content,
    }

Python code:

    import thriftpy

    docs_thrift = thriftpy.load("path_to_that_thrift", module_name="docs_thrift")
    enhanced_document = docs_thrift.EnhancedDocument()

    enhanced_document.title = docs_thrift.Document()
    enhanced_document.headline = docs_thrift.Document()
    enhanced_document.content = docs_thrift.Document()   

    enhanced_document.title.sentences.append(1)
    print enhanced_document.headline.sentences
    print enhanced_document.content.sentences

After running this code `title.sentences`, `headline.sentences` and `content.sentences` have one element.

How can I modify one list without modifying the others? Clearly, I can avoid this behavoiur by manually setting the`sentences` fields to empty list, but I was wondering if there are other solutions.

Thanks,
Marco

**Comment by lxyu** [comment]
The default value was coded in the generated function as default argument. In this case:

```
def __init__(self, sentences=[]):
    pass
```

I think it's because of the mutable default argument gotcha..

http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments

> Python’s default arguments are evaluated once when the function is defined, not each time the function is called

So, just don't do it.
