### ISSUE TITLE
Split problem

### ISSUE THREAD

**Issue by danteaeris** [eleme/thriftpy#216]
In `parser.py` The usage of `for name in p[n].split('.') ` causes problems when the "absolut name" contains multiples dots : 

> common.services.blabla.thrift.data.thrift.EventType1

Instead, you should use `for name in p[1].rsplit('.', 1)`

**Comment by hit9** [comment]
@danteaeris Hi, could you please paste some example codes here?

And I have tested the follow code, it's ok:

```thrift
/* file: shared.thrift */
enum Foo {
    VAL = 1,
}
```

```thrift
/* file: test.thrift */
include "shared.thrift"

const i32 val = shared.Foo.VAL
```

**Comment by lxyu** [comment]
Close for now, waiting for more information.
