### ISSUE TITLE
how can I compile thrift file to python file 

### ISSUE THREAD

**Issue by kooksee** [eleme/thriftpy#221]
I have a tutorial.thrift file,but how can I get the corresponding Python file？
thank you very much

**Comment by lxyu** [comment]
Simple answer, no you can't.

You can `load` the thrift file as a python module, which was dynamically generated. You may refer to [address.py](https://github.com/eleme/thriftpy/blob/develop/tests/addressbook.py) to get what the generated module looks like. But it can't generated a `.py` file, and there's no need to do so.
