### ISSUE TITLE
Add support for Thrift annotations.

### ISSUE THREAD

**Issue by dmitryzv** [eleme/thriftpy#273]
Currently doesn't have any support for annotations which are Thrift standard feature.
Should be able to load the [Apache test file](https://git-wip-us.apache.org/repos/asf?p=thrift.git;a=blob_plain;f=test/AnnotationTest.thrift;hb=HEAD
).

Loading this file now returns: _thriftpy.parser.exc.ThriftGrammerError: Grammer error '(' at line 20_

**Comment by hit9** [comment]
Hi, annotations are ignored by thriftpy (ref: https://github.com/eleme/thriftpy/pull/263).

The test thrift file should pass `thriftpy.load()` (except the `senum`, which is not supported by thriftpy).
