### ISSUE TITLE
Is the Tornado server asynchronous?

### ISSUE THREAD

**Issue by julioasotodv** [eleme/thriftpy#305]
I am trying to run the example in the docs (in `tornado.py`):

```python
pingpong = thriftpy.load("pingpong.thrift")
class Dispatcher(object):
    def ping(self):
        return "pong"

server = make_server(pingpong.PingPong, Dispatcher())
server.listen(6000)
```

This isn't asynchronous Tornado code (since there is no `@coroutine` decorator in the `Dispatcher`class, and it actuallty returns as any simple function).

Can be thriftpy's Tornado server asynchronous in any way?

**Comment by microdog** [comment]
The Tornado server implemented by thriftpy is asynchronous(using `tornado.tcpserver.TCPServer`). You can define methods with `@gen.coroutine` decorator or methods returning `Future` object.

```
class Dispatcher(object):
    @gen.coroutine
    def ping(self):
        yield gen.sleep(10)
        raise gen.Return("pong")
```

**Comment by julioasotodv** [comment]
Hi,

Yes, you are definetly right. I tried it before, but the problem was that I was trying to send lots of calls in parallel, but from the same client (which isn't async), so I couldn't be able to get benefit from async server side code.

Thank you very much. Great library btw :)
