### ISSUE TITLE
install failed in mac osx

### ISSUE THREAD

**Issue by wuyongyi** [eleme/thriftpy#331]
ld: in '/usr/local/lib/libunwind.dylib', file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libunwind.dylib for architecture i386
    clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/local/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/64/04r5rv8j2m96w_q58j125jhw0000gn/T/pip-install-iw0yt4so/thriftpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/64/04r5rv8j2m96w_q58j125jhw0000gn/T/pip-record-84ptd3zq/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/64/04r5rv8j2m96w_q58j125jhw0000gn/T/pip-install-iw0yt4so/thriftpy/

**Comment by ethe** [comment]
Fixed with [thriftpy2](https://github.com/Thriftpy/thriftpy2), this project was not supported any more.

**Comment by wuyongyi** [comment]
thanks for reply, I will look at thriftpy2.
