### ISSUE TITLE
客户端请求等待问题

### ISSUE THREAD

**Issue by vhysug** [eleme/thriftpy#336]
客户端请求后，服务端需要大量计算1min左右，此时客户端等待期间很容易卡死，有什么好的解决方法么？

**Comment by DavidMorre** [comment]
建议结合场景考虑此问题，如果是输入输出比较大的话，可以考虑使用支持streaming的rpc，比如GRPC。
如果是本身计算时间比较长的话，建议handler部分直接改成异步任务，rpc层面只是返回task的ID和状态，client不断轮询即可。
