### ISSUE TITLE
thriftpy client调用服务端的接口时报: <<class 'socket.error'>>:[Errno 4] Interrupted system call

### ISSUE THREAD

**Issue by lxl0928** [eleme/thriftpy#346]
![image](https://user-images.githubusercontent.com/12816246/48457260-f56aeb80-e7fc-11e8-906b-f525e7bff543.png)

server端是正常响应并创建的。日志如下图
![image](https://user-images.githubusercontent.com/12816246/48457279-10d5f680-e7fd-11e8-950a-6c95fd3b3325.png)

不报此错误，server端的日志如下图:
![image](https://user-images.githubusercontent.com/12816246/48457313-3531d300-e7fd-11e8-90b9-e80c30969b37.png)

多的get_face_list_by_id操作是我在报Interrupted system call错误后，在Exception处理业务里get_face_list_by_id了一次。

请教，client端为什么没有等create_face_list成功返回，就报上述错误，而且上述错误并不影响服务端的操作。

我该如何解决这个问题呢？

希望有前辈帮忙作答。

**Comment by ethe** [comment]
Could you please tell me how can I reproduce it?

**Comment by lxl0928** [comment]
目前只有我们线上环境会报此问题，线上部署方式为k8s集群部署: 

服务端: python3.6 + thriftpy + gunicorn_thrift                1个容器
客户端: python2.7 + thriftpy + thrift_connector              4个容器

服务端配置如下:
manage.py
```
# coding: utf-8

import logging.config

from thriftpy.thrift import TProcessor

from mle_basic import thrift_service
from mle_basic.settings import logging_config
from mle_basic.dispatchers.base import BasicServiceDispatcher

logging.config.dictConfig(logging_config)

service = thrift_service.BasicService
app = TProcessor(service=service, handler=BasicServiceDispatcher())
```

gunicorn_config.py如下:
```
# coding: utf-8

workers = 8
worker_class = "thriftpy_gevent"
thrift_protocol_factory = "thriftpy.protocol:TCyBinaryProtocolFactory"
thrift_transport_factory = "thriftpy.transport:TCyBufferedTransportFactory"

errorlog = '-'
```

启动脚本run-server.sh如下
```
#! /bin/sh

gunicorn_thrift manage:app -c gunicorn_config.py --bind 0.0.0.0:10000
```





客户端配置如下 basic_rpc.py:
```
# coding: utf-8

import os
import json
import logging

from thrift_connector import ClientPool, ThriftPyCyClient

from db_service import service   # severice为thriftpy.load("xxx.thrift")后的

BASIC_SERVICE_HOST = os.environ.get('BASIC_SERVICE_HOST', '0.0.0.0')
BASIC_SERVICE_PORT = int(os.environ.get('BASIC_SERVICE_PORT', 10000))
BASIC_SERVICE_TIMEOUT = 120  # 单位s, 2分钟


class BasicRPC(object):

    client = ClientPool(
        service=service.BasicService,
        host=BASIC_SERVICE_HOST,
        port=BASIC_SERVICE_PORT,
        timeout=BASIC_SERVICE_TIMEOUT,
        max_conn=30,
        connection_class=ThriftPyCyClient
    )
```



说明:

当我在本地mac pro 同时启动服务端rpc服务，然后在mac pro本地启动 客户端的项目开始调用时，并无法复现 `Interrupted system call`的问题。

我在Ubuntu Linux 16.04同时部署 服务端、客户端时，调用也是正常的，不会出现 `Interrupted system call`。

当我在阿里云 K8S同一个集群内，将服务端的rpc服务部署为一个容器， 将thriftpy的客户端部署为两个容器以上时，就会出现 `Interrupted system call`的问题，出现的评率，大致为: 我thriftpy client调用10次上面截图中的create_face_list，会引起2~5次的`Interrupted system call`.


总结:
单机目前无法复现此问题。

**Comment by ethe** [comment]
I think we have already fixed this issue, see https://github.com/Thriftpy/thriftpy2/pull/9/files

**Comment by lxl0928** [comment]
https://github.com/Thriftpy/thriftpy2/pull/9/files  在今年9月29日修复的此问题，好像还没有发布pypi包？
![image](https://user-images.githubusercontent.com/12816246/48477958-e7898a80-e83d-11e8-920a-5637c6f0594d.png)


感谢，我这边通过源码的方式更新一下，然后测试，测试pass后关掉此issue。

**Comment by ethe** [comment]
I will release it soon, thanks.

**Comment by ethe** [comment]
0.3.12 released, thanks.

**Comment by lxl0928** [comment]
感谢！

线上测试环境更新到0.3.12后没有再报过`Interrupted system call`的错误了。但是今天发现另外的一个问题。
![image](https://user-images.githubusercontent.com/12816246/48528400-c7071200-e8c9-11e8-8dbf-b854e851423a.png)


client端稳定调用server端的rpc一段时间后，就会出现: `TTransportException(message="Could not connect to ('192.168.160.61', 10000)", type=1)`

服务端失联的情形，但是报异常的前后都有调用服务端的接口成功的情况。

问题，出现失联情形，thriftpy + thrift_connector的socket重连机制依赖我们使用thriftpy的应用层代码去人为设置重新请求服务端接口吗？

**Comment by ethe** [comment]
Using keep-alive connections may be helpful to you, you do not need open connection in every request.

**Comment by ethe** [comment]
You can retry request manually.

**Comment by lxl0928** [comment]
Oh, thanks.
