### ISSUE TITLE
Need a release support service multiplexing

### ISSUE THREAD

**Issue by GuoJing** [eleme/thriftpy#94]
hello

I do need service multiplexing support, I found the commit `Added service multiplexing support.` is what I need, any plan?

Thanks

**Comment by lxyu** [comment]
@GuoJing v0.2 will be released within 2 days. : )

**Comment by GuoJing** [comment]
@lxyu thank you very much.

**Comment by lxyu** [comment]
v0.2.0 released.

**Comment by GuoJing** [comment]
Thank you man!

**Comment by lxyu** [comment]
You're welcome!
